fauna/faunadb-js

src/query.js
`varargsQuery` was unnecessarily complicated and wouldn't work for
functions that had other arguments in addition to the rest arg.
=> Cleanup handling of varargs

package.json, src/PageStream.js, src/model/Model.js, src/query.js, test/query_test.js
This is a breaking change, so we might need to tell the client about this / change the version number.
=> Move lambda arguments to the end to match faunadb-ruby

src/query.js, src/types/query.d.ts, test/query_test.js, test/util.js
I'm not sure if we should continue to have the driver internally join ref parts by `/` anymore anywhere, actually. It should probably just have the standard Ref() constructor, and the `{ ref: id: }` function form.
=> Add support for the true `ref` function

LICENSE, README.md, package.json
Bumps copyright date and updates github links for the org change.
Part of https://github.com/fauna/sales-engineering/issues/525.
=> Update driver info

CHANGELOG.md, src/errors.js
`this.constructor.name` is minified generating wrong error messages like "a: invalid data" instead of "BadRequest: invalid data".
=> Use literal strings as error class names

src/Client.js, test/query_test.js
This PR forces the `Content-Type` of request to `application/json` and serialize data to string before passing it to superagent so the library don't have to infer the data type.
This fixes the case when we just send primitive types and expect faunadb to echo these values.
=> force Content-Type to json and serialize data before send

CHANGELOG.md, src/query.js, test/query_test.js
This is a syntax sugar proposal. It avoid `q.Var` expressions when using `q.Let`.
Before:
```javascript
q.Let({ x: 1, y: 2 }, q.Add(q.Var("x"), q.Var("y")))
```
Now:
```javascript
q.Let({ x: 1, y: 2 }, (x, y) => q.Add(x, y))
```
=> Accept lambdas for let expression

test/client_test.js
`all` is too slow for the purpose of this test.
=> Use node scope for ping test

CHANGELOG.md, src/query.js, test/query_test.js
Returning a object was not possible. I've missed a `wrap` at the return of the lambda function.
=> Fix wrap of literal object for lambda form of let expression

CHANGELOG.md, index.d.ts
Fixes: #130 
Context: Typescript `export * from "./file"` exports everything except for the `default` export. Therefore, `Client` is not available to the typescript compiler, although present at runtime.
=> Fix typescript declaration file to include default types

package-lock.json
Simple wipe and recreate of the package-lock files. This is intended to fix the outstanding security vulnerabilities GitHub is reporting in this project's dependencies.
=> Update package lock files

src/Client.js, src/RequestResult.js, src/types/RequestResult.d.ts
The logger tests are failing. I realized that by using `JSON.stringify` we prevent it from pretty print requests to FaunaDB. Also, we were doing JSON serialization twice. I've split the raw JSON request from the executed query so the that logger can pretty print the query while the default node inspector can show the raw query string for debugging purpose.
=> Keep JSON request string stored at RequestResult

CHANGELOG.md, src/Client.js, test/clientLogger_test.js
this creates the branch `release-1.x` right before we introduce recursive references and set to the version 2.1.
=> Set api version to 2.0

CHANGELOG.md, src/Expr.js, src/values.js, test/values_test.js
Here are examples of the output generated by this change:
```javascript
Database("sub-db", Database("db"))
Index("spells_by_element_with_name")
Class("spells")
Class("cls", Database("db"))
SetRef({ match: Index("all_spells") })
Ref(Class("spells"), "201377948995944972")
Bytes("1234")
Date("2018-07-20T22:12:51.443072Z")
Date("2018-01-01")
{ ref: Function("fn", Database("db")),
ts: 1532123046028578,
name: 'fn',
body: Query({ lambda: 'x', expr: { var: 'x' } }) }
Ref(Keys(), "159541672656502790")
```
=> Pretty print Fauna objects

src/types/query.d.ts
This PR fixes a ts typing issue by changing `ExprVal`'s `object` to:
```ts
{
[key: string]: any;
}
```
Right now, if you run something like this:
```ts
q.CreateIndex({
name: "posts_by_date",
source: q.Class("posts"),
values: [{ field: ["data", "published_on"] }]
})
```
Typescript will complain:
```
Types of property 'values' are incompatible.
Type '{ field: string[]; }[]' is not assignable to type '() => IterableIterator<ExprVal>'.
Type '{ field: string[]; }[]' provides no match for the signature '(): IterableIterator<ExprVal>'.
```
I'm _pretty sure_ this is happening because the primitive type `object` matches an array:
```ts
// dummy.ts
function myFunction(foo: object) {}
myFunction({ hey: "there" }) // passes
myFunction([1,2,3])          // passes
myFunction("string")         // fails …
```
=> Fix index typing issue

src/types/RequestResult.d.ts
Fixes the `RequestResult` type to match the runtime.
=> Define constructor arguments of the RequestResult type as readonly properties

package.json, yarn.lock
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-471)
In this PR, I did the following to configure `browserify` to also output a ES Module:
1. Added the following packages: `babelify`, `@babel/core`, `@babel/preset-env` and `@babel/preset-react`
2. Update `browserify` script in `package.json` to output a `.es.js` file transformed by `babelify`
I tested this locally by going into my `faunadb-js` repo and:
1. Running `yarn link`
2. Setting up a CRA and running `yarn link faunadb`
3. Added the following to my `App.js`
```javascript
import faunadb, { query } from "faunadb";
```
4. Logged out `faunadb` and `query`. Got the following:
=> FE-471 | Configure browserify to output ES module

README.md, src/Client.js, test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-484)
**To Do:**
The work in this PR does the following:
1. Adds a `queryTimeout()` function to the `Client.prototype`, which allows users to set the `_queryTimeout` field on the Client instance
```javascript
const client = new faunadb.Client({
secret: 'MY_KEY'
})
client.queryTimeout(200)
```
2. Allows a user to pass a `queryTimeout` value to the `client.query()` function call, which will override `Client._queryTimeout` if it also has a value
```javascript
const data = client.query(q.Paginate(q.Collections()), { queryTimeout: 100 })
```
To test locally, I did the following:
1. In the local `faunadb-js` directory, run `yarn link`
2. In the local `console` repo, run `yarn link faunadb` 
3. At the root of `console`, create a `test.js`
4. …
=> FE-484 | Add queryTimeout to Client

src/types/errors.d.ts
Constructor typing for FaunaHTTPError in `errors.d.ts` doesn't match the constructor typing in `errors.js`, which makes subclassing FaunaHTTPError very difficult.  This PR seems to fix the issue without causing other problems, though I will confess that my testing has been minimal.  
[Jira Ticket]()
Fixes  #273
=> Fixing FaunaHTTPError constructor typing mismatch 

CHANGELOG.md, package-lock.json, package.json
**Changes**
- Fix type mismatch for FaunaHTTPError constructor
- Rollback ESM support breaking changes
=> chore(release): bump to 2.14.1

src/errors.js, test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-340)
This PR updates the error object returned from the JS Driver when a query fails for whatever reason:
- Takes the `description` from `RequestResult.responseRaw.errors` and adds it to the root of the response object
The ticket also asks for the `code` field from `RequestResult.responseRaw.errors` to be at the root of the object, but it already is (the field is named `message`). 
To test, I did the following:
1. Run `yarn link` in `faunadb-js`
2. Run `yarn link faunadb` in `console2`
3. In `console2`, create a `test.js` at the root of the project
4. Use the snippet below and run `node test.js` to execute the script
```javascript
const faunadb = require('faunadb')
const { query: q } = faunadb
const client = new faunadb.Client({ …
```
=> FE-340 | feat: add description to FaunaError

src/Expr.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-540)
The following FQL function names were improperly cased in the UDF form due to the logic below:
- `ContainsStr`
- `ContainsStrRegex`
- `StartsWith`
- `EndsWith`
- `RegexEscape`
- `FindStrRegex`
- `ReplaceStr`
- `FindStr`
```javascript
fn = fn
.split('_')
.map(function(str) {
return str.charAt(0).toUpperCase() + str.slice(1)
})
.join('')
```
The issue is that not all FQL function names come across the wire `in_snake_case`, so the logic above only capitalizes the first letter. Here's an example:
```javascript
// Wire protocol
replacestrregex
// Expected result
ReplaceStrRegex
// Actual result
Replacestrregex
```
1. Create a new UDF using one of the functions listed above
2. Save it
3. Confirm the form does not re-case the function …
=> FE-540 | Mis-cased FQL function names

README.md
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-645)
In our README, the unit of measure for the Client's `timeout` option was listed as milliseconds but is actually expecting a value in terms of seconds.
**Note:** Instead of this change, we could also make the `timeout` and `queryTimeout` options both be consistent and measure in milliseconds.
=> FE-645 | docs: fix timeout unit in README

src/Client.js, src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-630)
This PR adds a new FQL function called `ContainsPath` as part of API v3. For now, we are deprecating `Contains` and will plan on removing it completely in a future release.
=> FE-630 | Rename Contains to ContainsPath

src/Client.js, src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-652)
This PR adds the `ContainsField` function to our JavaScript driver. I have also included some test coverage that reflects how the [functionality is defined within Core](https://github.com/fauna/core/blob/09784957af4b33f597761ac768283f7a8eb6edbf/ext/api/src/test/scala/queries/BasicFunctionsSpec.scala#L1214).
The function takes two arguments:
1. A string representing the field to search for (rejects arrays, objects and numbers)
2. An object which we'll search its root for the field value
=> FE-652 | Add ContainsField

src/Expr.js, test/values.test.js
This reverts commit 5b6fa91cb53ffa82d2625314b625a947fa15d776.
This PR reverts [a previous PR](https://github.com/fauna/faunadb-js/pull/282/) which is causing errors with `Paginate` and `Match`, particularly in UDFs. I also experienced the same error when running unit tests while working on adding API v3 functions.
We are reverting this change for now because it is blocking our releases.
=> Revert "FE-625: Fix Paginate/Match rendering"

src/_json.js, src/types/values.d.ts, src/values.js, test/query.test.js, test/values.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-665)
**Additional specs:** https://faunadb.atlassian.net/browse/ENG-1941
This PR does the following:
1. Adds a `AccessProvider` document type
2. Adds definition of `AccessProvider` to TS types file
3. Implements logic for JSON parsing
4. Adds tests to cover instantiation and JSON parsing/encoding of `AccessProvider`
Run our local test suite: `npm run test`
=> FE-665 | Add AccessProvider document type and tests

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-663)
**Additional specs:** https://faunadb.atlassian.net/browse/DRV-124
This PR adds the `CreateAccessProvider` function 👍 
~Tests currently won't pass. I [need to get clarification re: how to test this function ](https://github.com/fauna/faunadb-js/pull/300#pullrequestreview-434210888)or remove the `create_access_provider` test block in `query.test.js`~
Run `npm run test`
=> FE-663 | Add CreateAccessProvider function

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-669)
This PR adds the `AccessProvider` function, which users can use to fetch providers they've previously created:
```
client.query(query.Get(query.AccessProvider("my-provider"))
```
Run `npm run test`
=> FE-669 | Add AccessProvider function

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-664)
This function allows users to query for the `AccessProvider`s they have set up in their database. They can use this function in one of two ways:
```
// Returns a single ref
client.query(query.Get(query.AccessProviders()))`
// Returns a list of refs
client.query(query.Paginate(query.AccessProviders()))`
```
This works pretty much the same way `Collections()` currently does 👍 
Run `npm run test`
=> FE-664 | Add AccessProviders function

src/Client.js, src/types/Client.d.ts
#268 has surfaced an error within **Client.query** expression parameter type. It is an `Expr` but should in fact be an `ExprArg` as it is converted to an `Expr` within the function itself.
You can find the discussion (30+ msgs) about it here: https://fauna-community.slack.com/archives/CLMPZHJ0G/p1591112108139900.
Wanna add anything to it? @ecwyne @BrunoQuaresma
=> Fix type of Client.query expression parameter from Expr to ExprArg

test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-673)
This PR updates some of the tests I wrote for the new API v3 functions we've been adding. **Before**, Core was not validating the `issue` field when a user was creating a new `AccessProvider`. **Now**, the URI must contain `auth0.com` to be considered valid.
Run `npm run test`
=> FE-673 | Update tests re: JWKS URI validation on Core

README.md
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-702)
This PR adds instructions to the README on how to use `npm pack` in order to create a local tarball and preview unreleased changes.
=> FE-702 | docs: add npm pack instructions

src/Expr.js, src/values.js, test/query.test.js, test/values.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-694)
This PR adds support for versions Query/Lambda values.
Run the test suite with `npm run test`
=> FE-694 | Supported versioned @query values

package.json
Last week, we tested this workflow with the `dryRun` flag and `semantic-release` was picking up v2.10.0 as our most recent tag and using that to decide what the new version number would be. This is strange since `git tag` and GitHub both show that our most recent tag is `2.14.2`.
In reading through the documentation, this is because semantic-release uses the tag format `vX.Y.Z` by default whereas our tags use `X.Y.Z` format.
=> chore: update release script

.github/workflows/semantic-release.yml
In our new release pipeline, `semantic-release` automatically creates a CHANGELOG and git tag, which we need to commit and then push back to our `master` branch to keep it up to date.
=> chore: add git changes to master branch after release

README.md, package.json
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-727)
This PR updates our GitHub Actions release pipeline by doing the following:
- Removing the `dryRun` flag from the semantic-release config in `package.json`
=> chore: remove dryRun flag in release config

src/query.js, src/types/query.d.ts, src/types/values.d.ts, src/values.js, test/query.test.js, test/values.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-714)
To prepare for API v3, we removed all of the `AccessProvider` functionality (#316) as the functionality is currently being reconsidered. This branch/PR represents all of the work we've done thus far.
=> FE-714 | Split AccessProvider work into its own branch

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-762)
This PR does the following:
- Adds `CurrentIdentity`, which has the same functionality as `Identity`
- Deprecates `Identity`
We cannot test this until the work in Core has been finished.
=> FE-762 | feat: add CurrentIdentity()

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-764)
This PR adds the `CurrentToken()` function to the JS Driver.
We cannot properly test this until the work is done in Core
=> FE-764 | feat: add CurrentToken()

src/query.js, src/types/query.d.ts, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-765)
This PR adds the `HasCurrentToken()` function and a stub for the tests.
This cannot be tested without the Core image being updated to include these new functions.
=> FE-765 | feat: add HasCurrentToken()

test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-777)
We are removing `Contains()` from Core in API v4, so we need to remove the tests before CI will pass.
=> FE-777 | Remove Contains() tests

src/Client.js, src/query.js, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-768)
**NOTE:** #339 needs to be merged first in order for these tests to pass CI
This PR updates the test coverage for `CreateAccessProvider` to reflect the new functionality. Specifically, we now have a `membership` field whose value is an array of Roles.
Using the `nightly` version of our Core image locally, you can run `npm run test`
=> FE-768 | Update tests for CreateAccessProvider

src/Client.js, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-788)
This PR adds tests for the following functions now that Core has implemented all the new FQL functionality:
- `CurrentToken`
- `HasCurrentToken`
- `CurrentIdentity`
- `HasCurrentIdentity`
Run `npm run test` with the latest nightly Docker image
=> FE-788 | Add API v4 tests

src/Expr.js
Tagging private functions so they don't appear in the library documentation.
=> Minor: mark internal functions as private for JSDoc

src/Client.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-804)
While testing out the preview of API v4, @fauna-brecht ran into an issue where he was receiving an `Unauthorized` response. @marrony determined this was due to us using `Basic` in our Authorization header instead of `Bearer`.
=> FE-804 | fix: change Basic to Bearer in Authorization header call

package-lock.json, package.json
This PR bumps the `version` in our `package.json` and `package-lock.json` from `3.0.1` to `4.0.0-preview` in preparation for publishing the API v4 preview to NPM 🚀
=> chore: bump to 4.0.0-preview.1

src/query.js, test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-815)
For AccessProviders, we decided to change the `membership` field to be called `roles` as this is more clear and self-documenting for the user.
~**NOTE:** These unit tests will not pass until we have an updated Docker image of Core that has also implemented these changes~
Cannot merge this until the Core image has streaming enabled by default -- until then tests won't pass.
=> FE-815 | Update AccessProviders 'membership' field to 'roles'

package-lock.json, package.json
Bump the JS Driver to `4.0.0-preview.2`, so folks can continue using our new Streaming features with the Preview environment
=> release: 4.0.0-preview.2

CHANGELOG.md
When we released `v4.0.0` today, the release pipeline didn't properly generate the CHANGELOG. This PR fixes that 👍
=> Update CHANGELOG for v4.0.0

src/_json.js, src/stream.js, test/_json.test.js, test/stream.test.js
To support for large JSON documents, we're moving from concatenated JSON objects to line-separated JSON streaming. This fix is intended to be backwards compatible while supporting the new line-separated format that is coming to cloud soon.
With a recent nightly build: 
* Create a document;
* Open a stream for it;
* Issue an updated with a relatively large JSON document (about 4KB or more).
Without this fix, the JSON parsing on the received version should break. With this path, you shall receive the updated version normally as part of the document stream.
We should release this fix once ENG-2431 is in cloud.
=> ENG-2431: Switch from contatenated to line-separated JSON

.gitignore, src/_util.js, src/errors.js, src/values.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-369)
NodeJS `util` package has been used for `.inherits` and `.inspect` functions. Current implementation supposes polyfilling `.inherits` function by created one in `src/_util.js` and optionally using `.inspect` only when we're running on NodeJS environment
No features / fixes have been introduced. Can be tested regression-wise
=> DRV-369: get rid of util nodejs package

src/_http.js, test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-376)
Current driver pass a 60 seconds timeout down to the `cross-fetch` polyfill. However, neither `whatwg-fetch` of `node-fetch` are aware of it. They both support abort signals, though: https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal.
=> DRV-376 Fix request timeout

src/stream.js
[Stream termination due to core's one-hour limit does not cause an error event](https://faunadb.atlassian.net/browse/DRV-365)
stream throw `end` event for nodejs and `error` event for the browser (tested at chrome). i suppose it would be a good idea if the driver will silently reconnect when such a case raised. 
to simulate the same behaviour as for browser, fix listen for `end` event and as soon as the event appears, fix convert it to an `error` event. 
```
const faunadb = require('./index')
const q = faunadb.query
const util = require('util')
var client = new faunadb.Client({
secret: 'XXXXXX'
})
;(async () => {
await client.query(
q.Paginate(q.Collections())
)
.then(ret => console.log(ret))
.catch(err => console.error('Error: %s', err))
})()
var stream
function startStream() {
stream = …
```
=> DRV-365 handle stream end the same fashion as for browser

src/Expr.js, test/values.test.js
This is related to this ticket:
[Jira Ticket](https://faunadb.atlassian.net/jira/software/c/projects/FE/issues/FE-642)
The code changes makes it possible for me to continue working, I'm currently working with a fork of this driver, do please check whether it doesn't break something else since I do not have that background on how the driver works. The PR is mainly here to  show where the problem is for the related ticket.
I have also exposed a function toFQL which I need for tooling. Feel free to separate both issues and/or rename it, doing a separate pull request is probably overkill.
If you choose not to make something like toFQL public, let me know, I'll have to include a chunk of code from the driver then in my tool.
=> Fix for stringification to FQL which inserted nulls for zero-argument AND expose toFQL

src/types/Client.d.ts, src/types/errors.d.ts, test/values.test.js
Hi. I would like to add some tiny improvements.
The first commit adds tiny Typescript improvements.
The second commit fixes a Test. 
As I live in Germany my Timezone is UTC+1. `new Date(1970, 0, 1)` will result in "1969-12-31T23:00:00.000Z" which won't match with "1970-01-01 ..." so that test failed on my machine. 
same as usual :)
=> Improve Typescript definitions and fix a date test

test/stream.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-444)
This fix doesn't introduce any changes to the client code, but rather adds missing tests to reflect that if there is an unexpected error in opened stream connection happened, we have 2 errors sent to the client: from onError and onEnd events.
=> chore: Added tests to reflect the error event delegation

package-lock.json, package.json, src/_http.js, src/stream.js, test/client.test.js
The issue can be reproduced if run faunadb-js at netlify functions.
Don't really know the root cause of this issue, but somehow related to CommonJS modules. Seems like netlify build stage use them rather then ES6 modules
This [repo](https://github.com/fireridlle/fauna-express) can be used as a code example
run netlify functions locally
```
npx netlify-lambda serve api/
```
open at the browser http://localhost:9000/.netlify/functions/index/fauna
or for streaming http://localhost:9000/.netlify/functions/index/debug-fauna-stream (only nodejs console logs available here)
Getting an error
```
(node:16784) UnhandledPromiseRejectionWarning: TypeError: o is not a constructor
at r.execute (/Users/szinkevych/projects/faunadb/fauna-express/functions/index.js:164:2194)
at d._execute …
```
=> Use abortcontroller polyfill

README.md
[DRV-445](https://faunadb.atlassian.net/browse/DRV-445)
Read the `README.md` file, click the doc links.
=> DRV-445: Update documentation links to use current URLs

package-lock.json, package.json, src/_http.js, src/_util.js
don't inject http,https,os,utils polyfills. they are required only inside condition isNodeEnv, so we are safe to remove them from the browser bundle
extract from the heavy url-parse package only what we need
Before
After
Note: screenshots above were made from non minified bundle. minified bundle about 78KB.
=> Decrease bundle size

package-lock.json, package.json, src/_http.js
[DRV-356](https://faunadb.atlassian.net/browse/DRV-356)
New headers applied for each request.
**X-Fauna-Driver-Version**
faunadb-js version (taken from package.json)
**X-Runtime-Environment**
name of runtime env (ex: Netlify, Vercel, etc..) or Unknown for an environment that can't be recognizable
**X-Runtime-Environment-OS**
Name of OS (ex: darwin, linux)
**X-NodeJS-Version**
Version of NodeJS
Currently disabled due to CORS error
**X-Fauna-Driver-Version**
faunadb-js version (taken from package.json)
**X-Runtime-Environment**
Browser name
**X-Runtime-Environment-Version**
Browser version
**X-Runtime-Environment-OS**
Name of OS (ex: darwin, linux)
=> DRV 356 recognize runtime env

README.md, package-lock.json, package.json, src/_http.js, src/_util.js, src/stream.js
Abort controller polyfill has been changed because of cloudflare issue
```
(node:16784) UnhandledPromiseRejectionWarning: TypeError: AbortController is not a constructor
at r.execute (/Users/szinkevych/projects/faunadb/fauna-express/functions/index.js:164:2194)
at d._execute (/Users/szinkevych/projects/faunadb/fauna-express/functions/index.js:325:32329)
at d.query (/Users/szinkevych/projects/faunadb/fauna-express/functions/index.js:325:31673)
```
However, that polyfill simply rejects a promise but not terminating a request. So we have to return the previous AbortController. Cloudflare team doesn't intend to implement AbortController https://community.cloudflare.com/t/timeout-with-fetch/25249/4. The possible workaround has been added to Readme.md
One more issue appears at Cloudflare, as …
=> Revert abort controller and more sophisticated nodejs env detection

src/Client.js, src/types/Client.d.ts, test/client.test.js
[DRV-437](Observer option passed to query is not handled)
issue: https://github.com/fauna/faunadb-js/issues/289
=> Accept observer for query

src/RequestResult.js, src/stream.js, src/types/Client.d.ts, src/types/RequestResult.d.ts, src/types/errors.d.ts
[DRV-435](https://faunadb.atlassian.net/browse/DRV-435)
Linked issues
https://github.com/fauna/faunadb-js/issues/384
https://github.com/fauna/faunadb-js/issues/341
tsconfig.json should have "lib": ['es2019']. in that case ts will not inject type for `fetch` (will only if lib has `DOM`)
No typescript error should be thrown
```javascript
import { Client, errors, FaunaHttpErrorResponseContent, query, values } from './index';
const client = new Client({
secret: '',
observer: (res => {
if((res.responseContent as FaunaHttpErrorResponseContent).errors) {
console.error('observer receive error')
console.error(res.responseContent)
}
})
})
client.query<values.FaunaTime>(query.Now())
.then(now => {
console.info('now ', now.date)
})
.catch((err: errors.FaunaHTTPError) => {
console.error('query catch …
```
=> Add missing type definitions

src/_http/index.js
Check if native http2 module is supported for older Node versions
Use the `nvm` tool to downgrade to older node versions
=> Check if native http2 module is supported for older Node versions

src/Expr.js, src/query.js, test/values.test.js
[DRV-511 expr to FQL logic seems flawed.](https://faunadb.atlassian.net/browse/DRV-511)
Fix incorrect optional params checks. 
Fix toString for `Merge`
```
console.info(new Query(
q.Merge(q.Select('data', q.Var('doc')), {
id: q.Select(['ref', 'id'], q.Var('doc')),
})
))
```
=> DRV-511 expr to FQL logic seems flawed.

package.json, src/Client.js, src/_http/http2Adapter.js, src/_http/index.js, test/client.test.js
[DRV-523](https://faunadb.atlassian.net/browse/DRV-523)
This is related to how http2 sessions work, a http2 session should be reused across multiple calls thus should have some lifetime specified. By default, it’s set to 60 secs which is reasonable for most web services (when having continuous incoming traffic). But unfortunately, I haven’t considered such cases like using fauna-shell - it definitely doesn’t make sense to keep this session for a long time in such scenarios.
The tricky question is to decide the reasonable/versatile lifetime for http2 sessions as the driver has a lot of use-cases in different environments. We could accept this http2 session lifetime via params when constructing the Client e.g. http2Lifetime but would it confuse the customer to configure it by themself? …
=> fix(htt2Adapter): set http2 session idle time

src/types/Client.d.ts
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-1142)
Fix type definition for Stream API to expose `.document` function from `Client#stream` one.
* try to access `Client#stream.document` property
* assert it has the same type signature as `Client#stream` function
=> FE-1142 - fix Stream API type definition (TypeScript)

src/Client.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-671)
Currently, it's not possible to get the API version of the JS driver. It's required for the FE ticket in order to show a warning in the case when versions differ. See Jira ticket for more details.
* try access `Client.apiVersion` static property
* assert it equals to package.json one
=> FE-671 - expose API version as a Client's static property

README.md, src/Client.js, src/_http/fetchAdapter.js, src/_http/http2Adapter.js, src/_http/index.js, test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-574)
Ensure removing timeout property and introducing `http2SessionIdleTIme` are reverted and no longer exists in the current version
=> DRV-574 - revert idle time and removing timeout

README.md, index.d.ts, package-lock.json, package.json, src/Client.js, src/index.js, src/stream.js, src/types/Client.d.ts, src/types/Stream.d.ts, stream/package.json, test/stream.test.js, tools/postBuildPackage.js, webpack.config.js
[DRV-556 Make streaming API independent of Client to not include it into a bundle by default.](https://faunadb.atlassian.net/browse/DRV-556)
Previous stream usage
```
const { Client } = require('faunadb')
const client = new Client();
const stream = client.stream.document(docRef)
```
New usage
```
const { Client, StreamAPI } = require('faunadb')
const client = new Client()
const streamApi = new StreamAPI({ client })
const stream = streamApi.document(docRef)
```
=> feature!: remove coupling between StreamApi and Client

src/_http/index.js, src/_util.js
[DRV-566 Cloudflare doesn't have navigator object](https://faunadb.atlassian.net/browse/DRV-566)
Issue: https://github.com/fauna/faunadb-js/issues/447
Running 4.1.2 produce an error at CloudFlare
```
ReferenceError: navigator is not defined
at Object.getBrowserDetails (worker.js:1:2773)
at worker.js:6:5260
at new s (worker.js:6:5461)
at new d (worker.js:6:17008)
at new a (worker.js:6:33478)
at s (worker.js:6:33984)
at Proxy.e.r (worker.js:6:14246)
at worker.js:6:34805
```
=> fix: cloudflare doesn't have navigator object

.circleci/config.yml
Repo contains package-lock.json, however, yarn is used to run tests on circleci. 
It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.
=> fix: use npm for test running

src/Client.js, src/_http/http2Adapter.js, src/_http/index.js, src/_util.js, test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-592)
Can be tested by writing a simple script with a fauna query and assert that after its execution fauna `Client` doesn't hold the event loop (the script is terminated after 500ms).
The following scripts have been used to load test inactivity mechanics by running parallel queries.
Perform `5000` parallel queries over `10` randomly selected `Client` instances:
```typescript
// inactivityTest.ts
require('dotenv').config()
import { Client, query as Q } from 'faunadb'
const SECRET = process.env.FAUNA_SECRET_ADMIN_KEY!
const getRandomInt = (min: number, max: number): number => {
min = Math.ceil(min)
max = Math.floor(max)
return Math.floor(Math.random() * (max - min + 1)) + min
}
const getRandomElement = <T>(list: T[]): T => …
```
=> DRV-592 - implement inactivity timeout for HTTP2 session

src/_http/http2Adapter.js, test/stream.test.js, test/util.js
Fixes calling `onSettled` callback twice for streaming requests by taking into account whether the request has already been canceled. The issue was that `onSettled` callback [was called](https://github.com/fauna/faunadb-js/blob/master/src/_http/http2Adapter.js#L209) unconditionally even if the request had already [been canceled](https://github.com/fauna/faunadb-js/blob/master/src/_http/http2Adapter.js#L265) (thus `onSettled` already [been called](https://github.com/fauna/faunadb-js/blob/master/src/_http/http2Adapter.js#L182)) which resulted in [ongoingRequest](https://github.com/fauna/faunadb-js/blob/master/src/_http/http2Adapter.js#L58) to be `-1` and not terminating the stream because [the condition](https://github.com/fauna/faunadb-js/blob/master/src/_http/http2Adapter.js#L100) isn't …
=> fix: DRV-592 - fix calling onSettled callback twice

src/errors.js
Remap 429 HTTP error to TooManyRequests error type
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-500)
Use the following script in order to reproduce `429` error:
```
;(async function () {
for (const _ of Array(30).fill(null)) {
await client
.query(
Q.CreateIndex({
name: String(Math.random()),
source: Q.Collection('items'),
}),
)
.catch(err => {
console.error(err)
process.exit(1)
})
}
console.log('Done')
})()
```
Note that `items` collection should have around 200 documents in order to trigger async index creation
=> DRV-500 - remap 429 HTTP error to TooManyRequests error type.

README.md
I tried visiting the FaunaDB JS Driver Reference Documentation link but was displayed this warning:
This PR updates the link in the readme to use .io instead!
Visit the link in the README!
=> Update github link to .io instead of .com

src/Expr.js, test/query.test.js, test/values.test.js
[DRV-482](https://faunadb.atlassian.net/browse/DRV-482)
If document data has a key with space, for example `"my key"`, it would break vs code extension to open such document as it's relly on `toString` implementation of js driver
JSON.parse(Expr.toString(query.Object({"my key": 11})))
or
1. insert document with such key to db collection
2. open this doc in vs code extenstion
=> fix: object with space in key to valid json

src/query.js, test/query.test.js
[DRV-208](https://faunadb.atlassian.net/browse/DRV-208)
Getting `Object expected, Object Provided` error when set a key to undefined.
Because Let does this,
```
Let({ message: "hey", key: undefined }, <expr>)` => `Let([ { message: "hey" }, { } ], <expr>)
```
```
query.Let({ x: 1, test: undefined }, query.Var('x')
```
=> fix: undefined value in let return an empty object

README.md, src/Client.js, src/_http/fetchAdapter.js, src/_http/http2Adapter.js, src/_http/index.js, src/errors.js, src/types/Client.d.ts, src/types/errors.d.ts, test/client.test.js, test/util.js
* implement the `Client#close` method to manually clean up an HTTP2 session
* allow `Infinity` for `http2SessionIdleTime` parameter
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-575)
The following script has been used to test the proper termination:
```typescript
// sample.ts
import { Client, query as Q } from 'faunadb'
const SECRET = process.env.FAUNA_SECRET_ADMIN_KEY!
const client = new Client({
secret: SECRET,
domain: 'db.fauna-preview.com',
scheme: 'https',
http2SessionIdleTime: Infinity,
})
client.query(Q.Now()).then(console.log)
setTimeout(() => {
console.log('Force closing...')
client.close()
}, 5 * 1000)
```
* run `ts-node sample.ts`
* assert script is terminated after around 5secs
=> DRV-575 - implement Client#close method

test/query.test.js
[Add additional tests for FQL functions](https://faunadb.atlassian.net/browse/OSS-377)
- scoped queries
- Lamda with 2 params
=> test: add missed tests for FQL queries

index.d.ts
[Missing TypeScript type for parseJSON](https://faunadb.atlassian.net/browse/OSS-742)
=> fix(OSS-742): pargeJSON types

src/types/Client.d.ts, src/types/errors.d.ts
Add `signal` property to client query option type
=> fix(types): add signal to query options and TooManyRequests

concourse/pipeline.yml
The variable defined in the concourse pipeline for npm token was incorrect
=> chore: Changed npm token vault variable name

CHANGELOG.md, package-lock.json, package.json
Make `signal` property of `client.query` optional
=> release: 4.4.1

src/_util.js
Fixed the changelog path by hardcoding the repository.
Fixes #533.
The path was not displaying properly because, when installing the package with npm, the file `package.json` contains the following:
```
"repository": {
"type": "git",
"url": "git+https://github.com/fauna/faunadb-js.git"
},
```
However, the local `package.json`, when developing on the project, contains the following:
```
"repository": "fauna/faunadb-js",
```
This is likely to be a normalisation transformation performed by npm when installing, which explains why the issue can be observed for users but not for developers.
I made the choice to hardcode the path to the repository because there is no documented substitute field in `package.json` that could contain `fauna/faunadb-js` (other than the homepage, which is already set …
=> Hardcode changelog path

src/Expr.js, test/query.test.js, test/values.test.js
[OSS-888](https://faunadb.atlassian.net/browse/OSS-888)
=> fix: ContainsStr FQL to string

src/values.js, test/values.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/OSS-906)
```javascript
var ref = new values.Ref("1234", "things")
console.log(ref._isFaunaExpr, ref._isFaunaValue, ref._isFaunaRef)
// result should be
true true true
```
=> OSS-906 fix: restore _isFaunaValue and _isFaunaRef properties

src/Client.js, test/client.test.js
[FE-1814]
Currently, the JS driver throws an error if the user is not connected to the internet when testing, which isn't the best user experience. The error is thrown by the FaunaDB client attempting to automatically check for new versions. Updating this to reverse the default version check gives a better user experience.
[FE-1814]: https://faunadb.atlassian.net/browse/FE-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change Client.js `checkNewVersion` default

concourse/scripts/publish_docs.sh
This PR adds configuration to avoid the consistently/uselessly failing builds for jsdoc. 
Those docs are currently managed via ConcourseCI.
Since the documentation gets regenerated and overwritten on each documentation deploy, the no-op configuration file must be generated and added to the repo before committing.
=> inject CircleCI config into `gh-pages`
