- package.json
`npm install faunadb/faunadb-js` should now work.
> Made the package installable from github.

- src/client.js
* delete does not take a 'data' param
* ping's parameters are optional
> Revise parameters of client methods.

- examples/package.json
(might not be available in windows)
> Change faunadb-test-es7 script to not use pipe 

- .gitignore
- README.md
- lib/AsyncStream.js
- lib/Client.js
- lib/PageStream.js
- lib/_json.js
- lib/_util.js
- lib/errors.js
- lib/model/Builtin.js
- lib/model/Codec.js
- lib/model/Field.js
- lib/model/Model.js
- lib/model/_util.js
- lib/objects.js
- lib/query.js
- package.json
Fixes https://github.com/faunadb/faunadb-js/issues/30
> Since the install script breaks in node 5.0.0, include `lib` in the repo instead

- examples/faunadb-test-es7.js
- examples/faunadb-test.js
- index.js
- package.json
> Added index.js and used it in examples

- src/query.js
Same as faunadb/faunadb-python#31
> Match query parameter names to docs

- src/query.js
- test/query_test.js
> Collection queries

- README.md
- src/Client.js
- src/types/Client.d.ts
- src/types/RequestResult.d.ts
- test/query_test.js
- test/util.js
we no longer need user/pass objects, so I'm removing it
> Remove basic auth object

- browserTest.conf.js
- mobileTest.conf.js
- package.json
So you can connect to it from mobile devices / emulated devices
> Add a remote karma target for mobile testing

- src/clientLogger.js
- test/clientLogger_test.js
There is really no good reason to expose this.
> Remove Credentials from clientLogger

- .gitignore
- package.json
somehow this got lost in a bunch of rebases
> add browserify target back

- README.md
- package.json
> Add package links

- README.md
- overview.md
- package.json
- src/Client.js
- src/errors.js
- src/query.js
- src/values.js
Part of https://github.com/faunadb/sales-engineering/issues/348.
Does not make any code changes.
> Update doc links

- .travis.yml
The old PR rotted, so I'm taking another shot at this.
> Readd JS driver to travis

- .gitignore
- .travis.yml
- README.md
- codecov.yml
- package.json
- test/page_test.js
> Add coverage to JS CI

- CHANGELOG.md
- src/query.js
- src/types/query.d.ts
- test/query_test.js
- test/util.js
As part of: https://github.com/faunadb/sales-engineering/issues/390
> Updating query language functions

- CHANGELOG.md
- src/errors.js
- src/query.js
- test/query_test.js
Closes: https://github.com/faunadb/sales-engineering/issues/379
> Restrict functions arity

- src/query.js
Fixes: https://github.com/faunadb/sales-engineering/issues/347
> Using Array.isArray for better runtime compatibility

- CHANGELOG.md
- src/query.js
- src/types/query.d.ts
- test/query_test.js
close https://github.com/fauna/sales-engineering/issues/493
> adds support for key_from_secret function

- CHANGELOG.md
- src/query.js
- src/types/query.d.ts
- test/query_test.js
close https://github.com/fauna/sales-engineering/issues/516
> adds support for at function

- README.md
> Add cdn tags to the README file

- CHANGELOG.md
- package-lock.json
- package.json
- src/query.js
- src/types/query.d.ts
- test/query_test.js
this pr includes
* `abort` function
* `casefold:` with `normalizer` parameter
* deprecate `next_id` function
* `new_id` function
* `singleton` function
* `events` function
* `identity` function
* `has_identity` function
> Adds missing functions

- CHANGELOG.md
- src/Client.js
> Show the raw query in the request result

- CHANGELOG.md
- src/Client.js
I have no clue what I'm doing here.
> Add support for X-Last-Seen-Txn.

- package-lock.json
- package.json
- src/Client.js
[CON-651]
fixes https://github.com/fauna/faunadb-js/issues/186
[CON-651]: https://faunadb.atlassian.net/browse/CON-651
> CON-651: [js] isomorphic-unfetch -> cross-fetch

- src/Client.js
[CON-654]
[CON-654]: https://faunadb.atlassian.net/browse/CON-654
> CON-654: [js] Require http/https only in node environments

- .eslintrc.yml
- README.md
- index.js
- package-lock.json
- package.json
- src/Client.js
- src/PageHelper.js
- test/client_test.js
- test/page_test.js
- test/query_test.js
- typings.json
[CON-669]
[CON-669]: https://faunadb.atlassian.net/browse/CON-669
> [CON-669]: Remove es6-promise dependency

- src/query.js
- src/types/query.d.ts
- test/query_test.js
[CON-580]
[CON-580]: https://faunadb.atlassian.net/browse/CON-580
> [CON-580]: Add ToObject()/ToArray()

- src/query.js
- src/types/query.d.ts
- test/query_test.js
[CON-594]
[CON-594]: https://faunadb.atlassian.net/browse/CON-594
> [CON-594]: Add Any()/All()

- src/query.js
- src/types/query.d.ts
- test/query_test.js
[CON-579]
Previously approved (`js-2.10`)
[CON-579]: https://faunadb.atlassian.net/browse/CON-579
> [CON-579]: Add TimeAdd(), TimeSubtract(), and TimeDiff()

- src/query.js
- src/types/query.d.ts
- test/query_test.js
- test/values_test.js
[CON-557]
Previously approved (`js-2.10`)
[CON-557]: https://faunadb.atlassian.net/browse/CON-557
> [CON-557]: Add SelectAsIndex()

- src/query.js
- src/types/query.d.ts
- test/query_test.js
[CON-602]
[CON-602]: https://faunadb.atlassian.net/browse/CON-602
> [CON-602]: Add ToDouble()/ToInteger()

- .eslintrc
- src/query.js
- src/types/query.d.ts
- test/query.test.js
- test/util.js
[CON-660]
[CON-660]: https://faunadb.atlassian.net/browse/CON-660
> [CON-660]: Add type check functions

- README.md
- src/Client.js
- src/PageHelper.js
- src/types/Client.d.ts
- src/types/PageHelper.d.ts
- test/client.test.js
[CON-650]
[CON-650]: https://faunadb.atlassian.net/browse/CON-650
> [CON-650]: Add query options

- src/Client.js
- src/RequestResult.js
- src/clientLogger.js
- src/types/Client.d.ts
- src/types/RequestResult.d.ts
- test/clientLogger.test.js
closes https://github.com/fauna/faunadb-js/issues/185
> ENG-1644: Remove client from RequestResult to not expose auth

- CHANGELOG.md
- README.md
- package.json
[CON-695]
[CON-695]: https://faunadb.atlassian.net/browse/CON-695
> CON-695: Prepare v2.9.4

- .circleci/config.yml
- This fixes the pipeline
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-272)
- Pipeline should be green
> Change release images for stable images

- package.json
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-412)
1. Open the JS driver repo
2. Create a `dist/faunadb-min.js`
3. Run `yarn run browserify-min`
4. Look at the output in `dist/faunadb-min.js` to confirm we're now seeing Fauna class and function names
> FE-412 | Prevent terser from uglifying class, func names

- yarn.lock
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-140)
> FE-140 | Fix security vulnerabilities

- CHANGELOG.md
- package.json
> chore(release): bump to 2.14.0

- package-lock.json
- package.json
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-587)
Reverts ESM support changes made as part of `2.14.0`
> FE-587 | chore: revert ESM changes

- README.md
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-566)
> FE-566-adds-example-to-connect-from-browser

- src/Client.js
- src/query.js
- src/types/query.d.ts
- test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-485)
**To Do:**
This PR adds a new `Reverse` function that takes a Set, Array or Page and returns the object's items in reverse order.
Run `npm run test` in your local repo to make sure the test suites pass
> FE-485 | Add Reverse function

- src/Client.js
- src/query.js
- src/types/query.d.ts
- test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-648)
This PR adds a new function to the JS driver called `ContainsValue`. This functionality has existed in the Core for a few weeks, but has yet to be added here.
To properly test this, you will need to make sure you're using the latest version of our `nightly` Docker image.
1. You can test this functionality by running our local test suite: `npm run test`
2. You could `yarn link` your local JS Driver repo to your local Console repo and use the webshell
> FE-684 | Add ContainsValue

- src/Client.js
- src/errors.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-638)
- Go to IE11 and try to use the driver
> refactor code to not use es6

- README.md
> docs(README): Add CircleCI build badge

- CHANGELOG.md
Updates the `CHANGELOG.md` for the changes made in the release of `v3.0.1`
> Update CHANGELOG for API v3

- test/query.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-766)
This PR will update the tests for `CreateAccessProvider` to reflect the new `membership` field, which is an array of Roles.
We cannot test this until the Core image has been updated to include API v4 functions
> FE-766 | chore: add todo for updating test

- src/Client.js
Links were missing or incorrect.
> Minor: fix ExprArg and query module reference in the Client docs

- src/Client.js
- src/_util.js
- src/query.js
I'll need this functions in a later PR so, I'm moving them to a common place.
> Minor: extract isNodeEnv and defaults to _util

- src/Client.js
- src/_http.js
- test/client.test.js
Depends on #346. I'll need this internal network layer in a later PR so, I'm extracting it to a separate module.
> Extract _http module from Client interface

- .circleci/config.yml
- package-lock.json
- package.json
- src/Client.js
- src/_http.js
- src/_util.js
- src/errors.js
- src/query.js
- src/stream.js
- test/client.test.js
- test/stream.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/ROAD-76)
This PR adds all of the work @erickpintor has done thus far on Streaming, so we can include it in the upcoming Driver preview.
> Add Streaming support to JS Driver

- package-lock.json
- package.json
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-806)
Update dependencies based on security warnings and `npm audit` output
> FE-806 | Update driver deps

- src/_json.js
- src/stream.js
- test/_json.test.js
JIRA Ticket: https://faunadb.atlassian.net/browse/ENG-2374
> handle multiple json objects in a message

- src/values.js
- test/values.test.js
> FE-830: Correctly renders collection refs with schema names

- .circleci/config.yml
- src/stream.js
- src/types/Client.d.ts
- src/types/Stream.d.ts
- test/stream.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-808)
Eric Wyne reported that our TS types were not updated when adding streaming support. This PR is intended to do that 👍
> FE-808 | Add TS types for streaming

- README.md
I don't know the Jira URL, so I opened a GitHub issue (#342) instead.
1. View rendered `README.md`.
2. Observe JavaScript code example under the 'Connecting from the browser' heading.
3. Ensure the `.catch` is chained to the object on the line above, and not to undefined `a`.
> Fix example code typo

- .circleci/config.yml
> chore: use public fauna image

- package-lock.json
- package.json
> chore: bump to 4.0.1

- package-lock.json
- package.json
> chore: bump to 4.0.2

- LICENSE
- README.md
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-329)
Nothing needs to be tested here, it's just a simple change in the readme file
> chore: Fixed copyright info

- package-lock.json
- package.json
> chore: bump to 4.0.3

- index.d.ts
- index.js
- src/_util.js
- src/types/query.d.ts
[Add named exports to query object](https://faunadb.atlassian.net/browse/DRV-399)
> Add named exports to query object

- package-lock.json
- package.json
> chore: bump to 4.1.0

- src/_http/index.js
[DRV-505 faunadb-js 4.1.0 release broke downstream products](https://faunadb.atlassian.net/browse/DRV-505)
> Fix merging headers

- package-lock.json
- package.json
> bump to 4.1.1

- test/auth.test.js
[DRV-543](https://faunadb.atlassian.net/browse/DRV-543)
Auth0 integration test works. However, auth0 return an error with status code 200 which lead to the promise resolved successfully and we proceed. In that case, the test failed with a not really clear message
> test: check auth0 setup correctly

- src/_http/index.js
- test/client.test.js
[Jira Ticket](https://faunadb.atlassian.net/browse/DRV-527)
See Jira ticket's comments for details
Try to pass `0` value when constructing the faunadb `Client`
> DRV-527: omit the port value if it's falsy

- package-lock.json
- package.json
- src/_http/index.js
- src/_util.js
- test/client.test.js
- test/stream.test.js
- test/util.js
[ROAD-466 Runtime env tracking](Runtime env tracking)
example
```
'X-Driver-Env': 'driverVersion=4.1.1; driver=nodejs; languageVersion=v12.18.0; env=unknown; os=darwin'
```
> feature: rework driver env header

- CHANGELOG.md
- package-lock.json
- package.json
> bump to 4.1.2

- CHANGELOG.md
- package-lock.json
- package.json
> bump to 4.1.3

- CHANGELOG.md
- package-lock.json
- package.json
> bump to 4.2.0

- .github/workflows/create-jira-tickets.yml
Step to check if a user in the organization return string type rather than boolean type
> fix: check if user in organization

- package-lock.json
- package.json
- test/auth.test.js
- test/config.js
- test/util.js
- tools/loadTest.js
[Load test](https://faunadb.atlassian.net/browse/DRV-562)
Before release, we need to check if the driver can perform under production load usage.
Create multiple clients and run multiple concurrent queries
```
npm run load-test -- --help
Options:
--help     Show help                                             [boolean]
--version  Show version number                                   [boolean]
-t, --threads  Maximum number of consequence threads    [number] [default: 10]
-q, --queries  Maximum number of queries per each thread [number] [default: 500]
```
> feature: load test

- index.js
[OSS-415](https://faunadb.atlassian.net/browse/OSS-415)
Related to https://github.com/fauna/faunadb-js/issues/222 and https://forums.fauna.com/t/handling-refs-ref-in-javascript/1398/2
This will make it easier for users to serialize and stringify FQL without having to import functions directly from the node_modules/faunadb/src directory.
> feature: expose parseJSON

- .github/workflows/complete-jira-ticket.yml
- .github/workflows/create-jira-tickets.yml
https://faunadb.atlassian.net/browse/OSS-729
I have not idea. I did this based on a code search and read. Not sure how to deploy it either.
> chore: Make Jira Tickets GitHub links clickable

- CHANGELOG.md
- package-lock.json
- package.json
- tools/printReleaseNotes.js
> bumped to 4.3.0 release

- index.html
Adds google tags manager tracking by manually change the `index.html` page,
finally, these snippets are going to be added by ci/cd system
[Jira Ticket](https://faunadb.atlassian.net/browse/OSS-682)
> feat(OSS-682): Add tracking to the drivers docs on Github

- README.md
[Jira Ticket](https://faunadb.atlassian.net/browse/OSS-776)
Check that link in the README.md file described in [this](https://github.com/fauna/faunadb-js/issues/503) issue is working
> fix(OSS-776): Fixed broken docs link

- src/Client.js
- src/_util.js
- src/types/Client.d.ts
- test/client.test.js
[OSS-772](https://faunadb.atlassian.net/browse/OSS-772)
[issue](https://github.com/fauna/faunadb-js/issues/502 )
Add option to skip driver version check
```
new Client({notifyAboutNewVersion: false})
```
> features(oss-722): option to disable checking driver version

- src/_http/http2Adapter.js
- test/client.test.js
[Fix false positive cases for ClientClosed error](https://faunadb.atlassian.net/browse/OSS-800)
> fix(OSS-800): enchange error message

- src/PageHelper.js
- test/page.test.js
[PageHelper drops the size parameter](https://faunadb.atlassian.net/browse/OSS-881)
fixes #514
> fix(OSS-881): PageHelper honors size with map/filter

- .github/workflows/complete-jira-ticket.yml
- .github/workflows/create-jira-tickets.yml
> fix: change utility github actions packages branch

- src/_util.js
Check linked issue for context
> fix: arrow fn

- CHANGELOG.md
- package-lock.json
- package.json
- src/Client.js
- src/_util.js
- src/types/Client.d.ts
- test/client.test.js
- Improve types (errors.pargeJSON, errors.TooManyRequests, `signal` for client.query options)
- Fix false positive cases for ClientClosed error
- Option to disable checking driver version (new Client({checkNewVersion: false}))
- Fix PageHelper honors size with map/filter
- Fix module issue for `Vitessedge`
> chore: release 4.4.0

- src/types/Client.d.ts
> fix(oss-897) optional signal

- package.json
- test/afterComplete.js
- test/query.test.js
- test/util.js
[OSS-92 Remove test resources after all test complated](https://faunadb.atlassian.net/browse/OSS-92)
> tests(OSS-92): remove resources after all test completed

- src/errors.js
- test/client.test.js
> Oss 1005 change Unauthorized message

- CHANGELOG.md
Include improvements to v4
- Upgraded Dependencies to address security concerns (https://github.com/fauna/faunadb-js/pull/600)
- Fix Auth0 (https://github.com/fauna/faunadb-js/pull/558)
- Fix `isFaunaValue` and `isFaunaRef` properties (https://github.com/fauna/faunadb-js/pull/529)
- Fix stack trace capture (https://github.com/fauna/faunadb-js/pull/536)
- Fix `ContainsStr` to render as string (https://github.com/fauna/faunadb-js/pull/537)
- Improve `Expr` type declaration to include `toFQL()` (https://github.com/fauna/faunadb-js/pull/544)
- Improve `PageHelper` (https://github.com/fauna/faunadb-js/pull/543)
- Improve unauthorized error message clarity (https://github.com/fauna/faunadb-js/pull/557)
> bump to 4.4.2

- src/stream.js
- src/types/Client.d.ts
- src/types/Stream.d.ts
- test/stream.test.js
Changes:
* New event type 'set' added;
* Added type information for set events;
* Test cases.
> ENG-3044: Introduce set streaming support

- CHANGELOG.md
- package-lock.json
- package.json
This is a release PR to introduce set-streaming support for the js driver.
> Bump to 4.5.0

- CHANGELOG.md
- package-lock.json
- package.json
- Address dependency security vulnerabilities [#606](https://github.com/fauna/faunadb-js/pull/606)
- Improve deployment pipeline [#612](https://github.com/fauna/faunadb-js/pull/612)
> bump to 4.5.1

- concourse/scripts/publish_docs.sh
The `config.yml` file needs to be created within a `.circleci` directory in order to be found by CircleCI.
> Navigate into `.circleci` directory

- CHANGELOG.md
- package-lock.json
- Fix documentation pipeline bug [#615](https://github.com/fauna/faunadb-js/pull/615)
- Fix webpack custom module bug [#614](https://github.com/fauna/faunadb-js/pull/614)
> bump to 4.5.2
